/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.XMLSerialization;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
    @XMLSerializable
    private static class DummyXMLSerializable {

    }

    private static class DummyNotXMLSerializable {

    }

    @Test
    public void testAnnotationOnClass() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.hasAnnotation(new DummyXMLSerializable()));
        assertFalse(classUnderTest.hasAnnotation(new DummyNotXMLSerializable()));
    }
}
