/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.fit.XMLSerialization;

public class Library {
    public boolean hasAnnotation(Object obj) {
        Class<?> classInfo = obj.getClass();
        return classInfo.isAnnotationPresent(XMLSerializable.class);
    }
}
